name: cocal
description: "Your personal health and nutrition tracking companion."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  riverpod: ^3.2.0
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  connectivity_plus: ^5.0.2
  intl: ^0.20.2
  fl_chart: ^1.1.1
  pdf: ^3.11.3
  excel: ^4.0.0
  flutter_local_notifications: ^17.2.4
  razorpay_flutter: ^1.3.7
  google_fonts: ^8.0.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  firebase_analytics: ^11.3.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "Assets.xcassets/AppIcon.appiconset"
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true
  
  assets:
    - assets/
